apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ansible-ee-tt
spec:
  params:
    - name: gitrevision
      description: The git revision (commit SHA)
    - name: short-id
      description: Truncated commit ID (used as tag)
    - name: gitrepositoryurl
      description: The Git repository URL

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ansible-ee-triggered-run-
        labels:
          tekton.dev/pipeline: ansible-builder
      spec:
        pipelineRef:
          name: ansible-builder
        serviceAccountName: pipeline
        timeout: 1h0m0s

        params:
          - name: ANSIBLE_BUILDER_IMAGE
            value: registry.redhat.io/ansible-automation-platform-25/ansible-builder-rhel8:latest
          - name: NAME
            value: quay.io/jtudelag/ansible-ee-test
          - name: TAG
            value: $(tt.params.short-id)
          - name: TLSVERIFY
            value: "false"
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
          - name: CONTEXT
            value: context/
          - name: DOCKERFILE
            value: Containerfile
          - name: BUILD_ARGS
            value: ""
          - name: PUSH_ARGS
            value: ""

        workspaces:
          - name: ee-repo
            persistentVolumeClaim:
              claimName: ansible-builder-pvc
